name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/lenchepetrov58/Cocktails
            azure-pipeline-name: 'github-actions-demo.yml'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
